name: Main

on: [push]

jobs:
  default:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.13', '1.14' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: { go-version: "${{ matrix.go }}" }
      - run: go test ./... -v
